### PR TITLE
Checking pagination using denserank

### PR DESCRIPTION
**Pull request by jlmc**

### CODE REVIEW

**Comment by jlmc** [comment]
I apologize for insisting on the same subject, but I am very interested in this feacture and it is not working successfully.

I forked your project and submeted this pull request. I added just some extra Asserts in the test PaginationTest # testFetchAndPaginateUsingDenseRank.

if you run the test case you can confirm that the list of comments is not filled correctly.

**Comment by vladmihalcea** [comment]
@jlmc I tested it too. The SQL is fine, but the column alias is lost in the derived-table so the PostComment gets the id from the Post. I'll see how to fix it.

**Comment by vladmihalcea** [comment]
@jlmc Check out [this commit](https://github.com/vladmihalcea/high-performance-java-persistence/commit/e4101d274ebc725743f32c2ec98158e4f693119f). I fixed the example. I'll update the article as well.

**Comment by jlmc** [comment]
@vladmihalcea Hi, very cool and simple solution, you are using a @SqlResultSetMapping :)

I have just one extra question: 

The comments is an ArrayList instance (we are defining this in the DistinctPostResultTransformer class).
The cascade mechanisms will works on post comments collection if we add or remove some comment?

**Comment by vladmihalcea** [comment]
Theoretically, it should work just fine. You can test it and see how it works.

**Comment by vladmihalcea** [comment]
[This commit](https://github.com/vladmihalcea/high-performance-java-persistence/commit/c2d4bdd9b74eec85040d3d17af2d32e2c85a7f98) fixes the problem with the INNER JOIN behavior.

**Pull request merged**
