### PR TITLE
Test case showing problem with two properties with SQL type OTHER when using Hibernate schema auto create

### PR DESCRIPTION
**Pull request by cigaly**
Hope that this can be useful to you. As I said, for me this is just kind of "puzzle". 

Regards,
Cedomir Igaly

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I quit working for Red Hat in 2019, so if there's a bug in Hibernate, you are better off opening a Hibernate issue and provide them a replicating test case.

**Comment by cigaly** [comment]
I've created this pull requet only because you've told me to do so several days ago. Sorry if I've misunderstood you.

And I do not think that this is a real bug, just a result of design. It will be too difficult to fix this without large redesign. I will rather check for other, more serious, bugs which Hibernate 6 have quite enough :-(

**Comment by vladmihalcea** [comment]
You can use the replicating test case for the Hibernate issue you're opening. It's just that this repository is for other purposes.

**Comment by cigaly** [comment]
As I've already said, I've obviously misunderstood you when you've said "Use my High-Performance Java Persistence GitHub repository to replicate the issue and send me a Pull Request with the problem".

Once again, sorry! I've surely did not wanted to cause any problems.

**Comment by vladmihalcea** [comment]
I thought you were referring to a configuration problem in Hibernate 6, not to a Hibernate bug.

**Pull request closed without merging**
